name: Test deploy canister

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - dev  
  workflow_dispatch: #auto test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and source DFX
        run: |
          DFXVM_INIT_YES=true sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
          echo 'source "$HOME/.local/share/dfx/env"' >> $GITHUB_ENV
          
      - name: Install frontend dependencies
        run: cd src/frontend && npm install
        
      - name: Start local replica
        run: dfx start --host 0.0.0.0:4943 --clean --background
        env:
         BASH_ENV: $HOME/.local/share/dfx/env
         
      - name: Deploy canisters (FE&BE)
        run: dfx deploy
        env:
         BASH_ENV: $HOME/.local/share/dfx/env
      #bisa tambahin step test lainnya:

      - name: Stop local replica
        run: dfx stop
